---

## This is a playbook for installing chrony  on specified hosts below Ansible
## Playbook uses "yum, service, and template, modules.
## This playbook was created by Joan Owusu (02/15/2018)


- hosts: chronytimeservers
  remote_user: ansible
  become: yes

  tasks:
  - name: install lastest chrony
    yum:
      name: chrony
      state: latest
  - name: write chrony config file
    template:
      src: /ansible/chronytemplate/chrony.conf.j2
      dest: /etc/chrony.conf
    notify:
    - restart chrony
  - name: ensure chrony service is running
    service:
      name: chronyd
      state: started
  handlers:
    - name: restart chrony
      service:
        name: chronyd
        state: restarted
