---

## This is a playbook for installing ntp on all anislbe clients using Ansible
## Playbook uses "yum, service, and template, modules.
## This playbook was created by Joan Owusu (02/15/2018)


- hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: install lastest ntp
    yum:
      name: ntp
      state: latest
  - name: write ntp config file
    template:
      src: /ansible/ntptemplate/ntp.conf.j2
      dest: /etc/ntp.conf
    notify:
    - restart ntp
  - name: ensure ntp service is running
    service:
      name: ntpd
      state: started
  handlers:
    - name: restart ntp
      service:
        name: ntpd
        state: restarted
